### Get All Posts
GET http://localhost:3000/api/posts

### Get Post By url
GET http://localhost:3000/api/posts/url

### Create New Post
POST http://localhost:3000/api/posts
Content-Type: application/json

{
    "title" : "titulo 2",
    "url": "url-2",
    "content": "contenido",
    "image" : "imagen"
}

### Update Post By url
PUT http://localhost:3000/api/posts/url-2
Content-Type: application/json

{
    "title" : "titulo 2",
    "url": "url-2",
    "content": "contenido",
    "image" : "imagen"
}

### Delete Post By url
DELETE http://localhost:3000/api/posts/url-2

# Crud Users

### Get All User
GET http://localhost:3000/api/users

### Get User By username
GET http://localhost:3000/api/users/hdiaz

### Create New User
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "hdiaz",
    "email": "hdiaz@nectia.com",
    "password": "hdiaz123"
}

### Update Post By url
PUT http://localhost:3000/api/users/hdiaz
Content-Type: application/json

{
    "username" : "hdiaz",
    "email": "hdiaz@gmail.com",
    "password": "hdiaz1234",
    "posts": [
        "5f3c08ff6e0ae828fd924fc3"
    ]
}

### Delete Post By url
DELETE http://localhost:3000/api/users/hdiaz